import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Material Design 3 tokens del DESIGN.md de Stitch
        surface: '#f6fbf2',
        'surface-dim': '#d6dcd3',
        'surface-bright': '#f6fbf2',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f5ec',
        'surface-container': '#eaf0e6',
        'surface-container-high': '#e4eae1',
        'surface-container-highest': '#dfe4db',
        'on-surface': '#171d17',
        'on-surface-variant': '#3f4a3f',
        'inverse-surface': '#2c322c',
        'inverse-on-surface': '#edf2e9',
        outline: '#6f7a6e',
        'outline-variant': '#becabc',
        'surface-tint': '#006d31',
        primary: '#00622b',
        'on-primary': '#ffffff',
        'primary-container': '#0a7d3a',
        'on-primary-container': '#bcffc3',
        'inverse-primary': '#78db8c',
        secondary: '#006c49',
        'on-secondary': '#ffffff',
        'secondary-container': '#6cf8bb',
        'on-secondary-container': '#00714d',
        tertiary: '#943048',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#b3485f',
        'on-tertiary-container': '#ffeaec',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#94f8a6',
        'primary-fixed-dim': '#78db8c',
        'on-primary-fixed': '#00210a',
        'on-primary-fixed-variant': '#005323',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        'tertiary-fixed': '#ffd9dd',
        'tertiary-fixed-dim': '#ffb2bd',
        'on-tertiary-fixed': '#400014',
        'on-tertiary-fixed-variant': '#82223b',
        background: '#f6fbf2',
        'on-background': '#171d17',
        'surface-variant': '#dfe4db',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        margin: '24px',
        gutter: '20px',
      },
      fontFamily: {
        h1: ['Inter', 'sans-serif'],
        h2: ['Inter', 'sans-serif'],
        h3: ['Inter', 'sans-serif'],
        'body-base': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'data-mono': ['"JetBrains Mono"', 'monospace'],
        'api-snippet': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        h1: ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        h2: ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-base': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'data-mono': ['14px', { lineHeight: '1.4', fontWeight: '500' }],
        'api-snippet': ['13px', { lineHeight: '1.7', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
export default config;
